---
x-chatwoot-env: &chatwoot_env
  - FRONTEND_URL=${CHATWOOT_FRONTEND_URL}
  - SECRET_KEY_BASE=${CHATWOOT_SECRET_KEY_BASE}
  - POSTGRES_DATABASE=chatwoot_production
  - POSTGRES_HOST=chatwoot-db
  - POSTGRES_USERNAME=${CHATWOOT_DB_USER}
  - POSTGRES_PASSWORD=${CHATWOOT_DB_PASSWORD}
  - REDIS_URL=redis://default:${CHATWOOT_REDIS_PASSWORD}@chatwoot-valkey:6379
  - RAILS_ENV=production
  - INSTALLATION_ENV=docker
  - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
  - SMTP_ADDRESS=${SMTP_ADDRESS}
  - SMTP_USERNAME=${SMTP_USERNAME}
  - SMTP_PASSWORD=${SMTP_PASSWORD}

services:
  chatwoot-db:
    # Recuerda que en tu .env ahora es pgvector/pgvector:pg17
    image: ${CHATWOOT_DB_IMAGE:-pgvector/pgvector:pg17}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${CHATWOOT_DB_USER}
      POSTGRES_PASSWORD: ${CHATWOOT_DB_PASSWORD}
      POSTGRES_DB: chatwoot_production
    volumes:
      - chatwoot_db_data:/var/lib/postgresql/data
    networks:
      - chatwoot_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
  # After run "docker compose up -d" execute:
  # docker compose run --rm chatwoot-web bundle exec rails db:chatwoot_prepare
  chatwoot-valkey:
    image: ${CHATWOOT_VALKEY_IMAGE:-valkey/valkey:9.0.3}
    restart: unless-stopped
    command: ["valkey-server", "--requirepass", "${CHATWOOT_REDIS_PASSWORD}"]
    volumes:
      - chatwoot_valkey_data:/data
    networks:
      - chatwoot_net
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli -a ${CHATWOOT_REDIS_PASSWORD} ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  chatwoot-web:
    image: ${CHATWOOT_IMAGE:-chatwoot/chatwoot:v4.12.1}
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      chatwoot-db:
        condition: service_healthy
      chatwoot-valkey:
        condition: service_healthy
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    environment: *chatwoot_env
    volumes:
      - chatwoot_storage:/app/storage
    networks:
      - chatwoot_net
      - public_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  chatwoot-worker:
    image: ${CHATWOOT_IMAGE:-chatwoot/chatwoot:v4.12.1}
    restart: unless-stopped
    depends_on:
      chatwoot-db:
        condition: service_healthy
      chatwoot-valkey:
        condition: service_healthy
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    environment: *chatwoot_env
    volumes:
      - chatwoot_storage:/app/storage
    networks:
      - chatwoot_net
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[s]idekiq' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chatwoot_db_data: {}
  chatwoot_valkey_data: {}
  chatwoot_storage: {}
networks:
  public_net:
    external: true
  chatwoot_net:
    driver: bridge
