---
# Ansible Galaxy collections required for NIST Hardening Suite

collections:
  - name: community.general
    version: "8.3.0"
  - name: community.sops
    version: "1.6.7"
  - name: ansible.posix
    version: "1.5.4"
  - name: community.docker
    version: "3.10.0"

  # To install:
  #   ansible-galaxy collection install -r requirements.yml
  # Or use ansible-galaxy directly:
  #   ansible-galaxy collection install community.general community.sops
  #   ansible.posix community.docker
